### ISSUE TITLE
Is there anything I should do before training.

### ISSUE THREAD

**Issue by Carus501** [Bureaux-Tao/ccksyidu4k-ner-albert#1]
When I start training by "python train.py" in the cmd.
I got "tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for D:\CollegeBusiness\Graduation Research\ccksyidu4k-ner-roformer\ccksyidu4k-ner-roformer./chinese_roformer-v2-char_L-12_H-768_A-12/bert_model.ckpt"

I look back and found there no "bert_model.ckpt" under any file, and the structure of 'chinese_roformer-v2-char_L-12_H-768_A-12' file is also a little different, there are some files missing.

So I am wondering if there's something I did wrong.

**Comment by Bureaux-Tao** [comment]
> When I start training by "python train.py" in the cmd. I got "tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for D:\CollegeBusiness\Graduation Research\ccksyidu4k-ner-roformer\ccksyidu4k-ner-roformer./chinese_roformer-v2-char_L-12_H-768_A-12/bert_model.ckpt"
> 
> I look back and found there no "bert_model.ckpt" under any file, and the structure of 'chinese_roformer-v2-char_L-12_H-768_A-12' file is also a little different, there are some files missing.
> 
> So I am wondering if there's something I did wrong.

Download the weights file first.
small: https://open.zhuiyi.ai/releases/nlp/models/zhuiyi/chinese_roformer-v2-char_L-6_H-384_A-6.zip
base: https://open.zhuiyi.ai/releases/nlp/models/zhuiyi/chinese_roformer-v2-char_L-12_H-768_A-12.zip
large: https://open.zhuiyi.ai/releases/nlp/models/zhuiyi/chinese_roformer-v2-char_L-24_H-1024_A-16.zip
